file = open('9-File-Handling/file1.txt','w')
open('9-File-Handling/file2.py','w')
open('9-File-Handling/file3.java','w')
open('9-File-Handling/file4.xsl','w')
open('9-File-Handling/file5.json','w')
open('9-File-Handling/file6.html','w')
open('9-File-Handling/file7.word','w')
open('9-File-Handling/file8.xml','w')
open('9-File-Handling/file9.csv','w')
open('9-File-Handling/file10.sql','w')